# Generated by Django 2.2.10 on 2020-09-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_change_shape_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='times_annotated',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
