# Generated by Django 2.2.10 on 2020-10-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_add_multiple_versions_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='concurrent_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
