# Generated by Django 2.2.10 on 2020-09-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_add_multiple_versions_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
