# Generated by Django 2.2.10 on 2020-09-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0026_task_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
