# Generated by Django 2.2.10 on 2020-10-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0027_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='concurrent_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
