version: "2.3"
services:
  cvat_proxy:
    environment:
      CVAT_HOST: cvat.daedalean.ai
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from grey"
      UI_SCHEME: https
      UI_HOST: cvat.daedalean.ai
      UI_PORT: 443
    volumes:
      - cvat_share:/home/django/share:ro
volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/grey/
      o: bind
