version: "2.3"
services:
  cvat_proxy:
    environment:
      CVAT_HOST: cvat.daedalean.ai
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from grey"
      UI_SCHEME: https
      UI_HOST: cvat.daedalean.ai
      UI_PORT: 443
      INVENTORY_CREDENTIALS_FILENAME: cvat-inentory-file-writer-948543f62305.json
      INVENTORY_SPREADSHEET_ID: 11nn8OJlvMllfpF8qkcLqbvefclF0iIiawFO9xN-2MrI
    volumes:
      - cvat_share:/home/django/share:rw
    build:
      args:
        UID: 848400089
volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/grey/
      o: bind
