version: "2.3"

services:
  run_tests:
    image: node:12-alpine
    stdin_open: true
    volumes:
      - ./cvat-core:/app
    working_dir: /app
    environment:
        NODE_PATH: /app/node_modules
#    command: npm run test
    command: sh -c "npm install && npm run build"
